---
title: "Spatial Descriptive Measures of Obesity"
output: 
  html_document
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r}
start.time = Sys.time()
pkgs = c("dplyr", "ggplot2", "tidyr", "readr", "crayon", "tibble", "knitr", "gt", "broom",
         "tidyverse", "sf", "tmap", "aspace", "spdep", "corrplot", "readxl", "spatialreg")
invisible(lapply(pkgs, function(pkg) {
  suppressPackageStartupMessages(library(pkg, character.only = TRUE))
}))
rm(pkgs)
if (requireNamespace("rstudioapi", quietly = TRUE)) {
  setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
}
```

```{r}
# saveRDS(sg_crs, "InteractivePlots/sg_crs.rds")
obesity_data_sf_2023_OSO <-
  readRDS("~/Desktop/RStudio/Spatial Data DSA303 codes/dsa303/InteractivePlots/obesity_data_sf_2023_OSO.rds")
sg_crs <-
  readRDS("~/Desktop/RStudio/Spatial Data DSA303 codes/dsa303/InteractivePlots/sg_crs.rds")
```

```{r}
### by Primary School

tmap_mode("view")

# filter out by educational level and remove NA values to calculate SDE
obesity_pri_sch <- obesity_data_sf_2023_OSO %>% 
  filter(LEVEL == "PRIMARY", !is.na(PREVALENCE))

# Mean centre, standard deviation distance, standard deviation ellipse
pri_sch_mean <- calc_mnc(id = 1, points = st_coordinates(obesity_pri_sch))
pri_sch_median <- calc_mdc(id = 2, points = st_coordinates(obesity_pri_sch))
pri_sch_mean_median <- rbind(pri_sch_mean$LOCATIONS, pri_sch_median$LOCATIONS) %>%
  data.frame() %>% 
  st_as_sf(coords = c("x", "y"), crs = sg_crs)
pri_sch_mean_median$id <- c("Spatial mean", "Spatial median")

pri_sch_sdd <- calc_sdd(id = 3, points = st_coordinates(obesity_pri_sch))
pri_sch_sdd_line <- pri_sch_sdd$LOCATIONS %>% 
  st_as_sf(coords = c("x", "y"), crs = sg_crs) %>% 
  st_combine() %>% 
  st_cast("LINESTRING")

pri_sch_sde <- calc_sde(id = 4, points = st_coordinates(obesity_pri_sch))
# pri_sch_sde$ATTRIBUTES[,10] # theta = 92.55625
pri_sch_sde_line <- pri_sch_sde$LOCATIONS %>% 
  st_as_sf(coords = c("x", "y"), crs = sg_crs) %>% 
  st_combine() %>% 
  st_cast("LINESTRING")

pri_sch_sde_weighted <- calc_sde(
  id = 5, calccentre = T, weighted = T, weights = obesity_pri_sch$PREVALENCE,
  points = st_coordinates(obesity_pri_sch))
pri_sch_sde_weighted_line <- pri_sch_sde_weighted$LOCATIONS %>% 
  st_as_sf(coords = c("x", "y"), crs = sg_crs) %>% 
  st_combine() %>% 
  st_cast("LINESTRING")

pri_sch_map <- 
  tm_shape(obesity_pri_sch, name = "Overweight prevalence") +
  tm_symbols(
    size = "PREVALENCE",
    size.scale = tm_scale_continuous(values.scale = 0.8),
    size.legend = tm_legend_hide(),
    fill = "PREVALENCE", 
    fill.scale = tm_scale(
      breaks = c(0, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30), 
      values = "brewer.yl_or_rd"
      ), 
    fill.legend = tm_legend(
      title = "Overweight prevalence", 
      position = c("BOTTOM", "LEFT"), 
      item.height = 0.5, 
      item.width = 2.1
      )
    )

pri_sch_map_summ <- pri_sch_map +
  tm_shape(pri_sch_sdd_line, name = "SDD") + tm_lines(lwd = 2, lty = 1) +
  tm_shape(pri_sch_sde_line, name = "SDE") + tm_lines(lwd = 2, lty = 3) +
  tm_shape(pri_sch_sde_weighted_line, name = "weighted SDE") + 
  tm_lines(col = "red", lwd = 2, lty = 3) +
  tm_shape(pri_sch_mean_median, name = "Summary measures") + 
  tm_dots(size = 0.5, shape = "id", fill = "white", shape.legend = tm_legend("Summary measures")) + 
  tm_add_legend(type = "lines", labels = "weighted SDE", lty = 3, col = "red") +
  tm_add_legend(type = "lines", labels = "SDE", lty = 3) +
  tm_add_legend(type = "lines", labels = "SDD", lty = 1) +
  tm_title("Overweight prevalence in Primary Schools")

### by Secondary School

# filter out by educational level and remove NA values to calculate SDE
obesity_sec_sch <- obesity_data_sf_2023_OSO %>% 
  filter(LEVEL == "SECONDARY", !is.na(PREVALENCE))

# Mean centre, standard deviation distance, standard deviation ellipse
sec_sch_mean <- calc_mnc(id = 1, points = st_coordinates(obesity_sec_sch))
sec_sch_median <- calc_mdc(id = 2, points = st_coordinates(obesity_sec_sch))
sec_sch_mean_median <- rbind(sec_sch_mean$LOCATIONS, sec_sch_median$LOCATIONS) %>% 
  data.frame() %>% 
  st_as_sf(coords = c("x", "y"), crs = sg_crs)
sec_sch_mean_median$id = c("Spatial mean", "Spatial median")

sec_sch_sdd <- calc_sdd(id = 3, points = st_coordinates(obesity_sec_sch))
sec_sch_sdd_line <- sec_sch_sdd$LOCATIONS %>% 
  st_as_sf(coords = c("x", "y"), crs = sg_crs) %>% 
  st_combine() %>% 
  st_cast("LINESTRING")

sec_sch_sde <- calc_sde(id = 4, points = st_coordinates(obesity_sec_sch))
# sec_sch_sde$ATTRIBUTES[,10] # theta = 92.3718
sec_sch_sde_line <- sec_sch_sde$LOCATIONS %>% 
  st_as_sf(coords = c("x", "y"), crs = sg_crs) %>% 
  st_combine() %>% 
  st_cast("LINESTRING")

sec_sch_sde_weighted <- calc_sde(
  id = 5, calccentre = T, weighted = T, weights = obesity_sec_sch$PREVALENCE,
  points = st_coordinates(obesity_sec_sch))
sec_sch_sde_weighted_line <- sec_sch_sde_weighted$LOCATIONS %>% 
  st_as_sf(coords = c("x", "y"), crs = sg_crs) %>% 
  st_combine() %>% 
  st_cast("LINESTRING")

sec_sch_map <- 
  tm_shape(obesity_sec_sch, name = "Overweight prevalence") +
  tm_symbols(
    shape = 22,
    size = "PREVALENCE",
    size.scale = tm_scale_continuous(values.scale = 0.8),
    size.legend = tm_legend_hide(),
    fill = "PREVALENCE", 
    fill.scale = tm_scale(
      breaks = c(0, 0.05, 0.10, 0.15, 0.20, 0.25, 0.30),
      values = "brewer.yl_or_rd"
      ), 
    fill.legend = tm_legend(
      title = "Overweight prevalence",
      position = c("BOTTOM", "LEFT"),
      item.height = 0.5, item.width = 2.1
      )
    )

sec_sch_map_summ <- sec_sch_map +
  tm_shape(sec_sch_sdd_line, name = "SDD") + tm_lines(lwd = 2, lty = 1) +
  tm_shape(sec_sch_sde_line, name = "SDE") + tm_lines(lwd = 2, lty = 3) +
  tm_shape(sec_sch_sde_weighted_line, name = "weighted SDE") + 
  tm_lines(col = "red", lwd = 2, lty = 3) +
  tm_shape(sec_sch_mean_median, name = "Summary measures") + tm_dots(
    size = 0.5, shape = "id", fill = "white", 
    shape.legend = tm_legend("Summary measures")
    ) + 
  tm_add_legend(type = "lines", labels = "weighted SDE", lty = 3, col = "red") +
  tm_add_legend(type = "lines", labels = "SDE", lty = 3) +
  tm_add_legend(type = "lines", labels = "SDD", lty = 1) +
  tm_title("Overweight prevalence in Secondary Schools")

tmap_arrange(pri_sch_map_summ, sec_sch_map_summ, nrow = 1)
```

The standard deviational ellipse, when accounting for school obesity (red band), is being "pulled" towards the North. (spatial clustering of high obesity schools)