---
title: "Spatial Descriptive Measures of Obesity"
output: 
  html_document
editor_options: 
  chunk_output_type: console
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r}
start.time = Sys.time()
pkgs = c("dplyr", "ggplot2", "tidyr", "readr", "crayon", "tibble", "knitr", "gt", "broom",
         "tidyverse", "sf", "tmap", "aspace", "spdep", "corrplot", "readxl", "spatialreg")
invisible(lapply(pkgs, function(pkg) {
  suppressPackageStartupMessages(library(pkg, character.only = TRUE))
}))
rm(pkgs)
if (requireNamespace("rstudioapi", quietly = TRUE)) {
  setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
}
```

```{r}
# saveRDS(sg_crs, "InteractivePlots/sg_crs.rds")
obesity_data_sf_2023_OSO <-
  readRDS("~/Desktop/RStudio/Spatial Data DSA303 codes/dsa303/InteractivePlots/obesity_data_sf_2023_OSO.rds")
sg_crs <-
  readRDS("~/Desktop/RStudio/Spatial Data DSA303 codes/dsa303/InteractivePlots/sg_crs.rds")
```

```{r}
###Primary School Z-Score Change Map for Model 1
library(tidyverse)
library(imputeTS)  # For interpolation
library(fpp2)
library(gridExtra)
library(seasonal)
library(urca)
library(vars)
library(trend)
library(readxl)
library(dplyr)

oso_pri_hist = read_excel("DataFiles/oso_primary.xlsx")

oso_pri_hist_years = oso_pri_hist[, c(1,2, 18, 20, 22, 24, 26, 28)] %>%
  drop_na()
  

oso_pri_hist_long <- oso_pri_hist_years %>%
  pivot_longer(
    cols = matches("^\\d"),   # Select columns where names start with a number
    names_to = "year",
    values_to = "oso"
  ) %>%
  mutate(year = as.integer(paste0("20", str_extract(year, "^\\d{2}"))))  


oso_hist_int = oso_pri_hist_long %>%
  group_by(SCHOOL) %>%
  complete(year = full_seq(year, 1)) %>%  # Adds missing years with NA values
  mutate(oso = na_interpolation(oso, option = "spline"),
         oso_int = na_interpolation(oso, option = "spline")) %>%
  ungroup() 

# Showing general distribution of OSO in a histogram
oso_hist_int %>% 
  filter(year == 2023) %>% 
  ggplot(aes(x = oso_int)) +
  geom_histogram() # generally follows a normal distribution

#Get the Z-scores
# Compute z-scores before and after 2019
oso_hist_int = oso_hist_int %>%
  group_by(year) %>%  # Group by year
  mutate(
    mean_oso = mean(oso_int, na.rm = TRUE),
    sd_oso = sd(oso_int, na.rm = TRUE),
    z_score = (oso_int - mean_oso) / sd_oso
  ) %>%
  ungroup()

# Label the periods
oso_hist_int_2 <- oso_hist_int %>%
  mutate(period = ifelse(year <= 2019, "Before 2019", "After 2019"))

z_scores_summary <- oso_hist_int_2 %>%
  group_by(SCHOOL, period) %>%
  summarise(avg_z = mean(z_score, na.rm = TRUE)) %>%
  ungroup()

z_scores_change= z_scores_summary %>%
  pivot_wider(names_from = period, values_from = avg_z) %>%
  mutate(z_change =`After 2019` - `Before 2019`) %>%
  dplyr::select(c(1,4))


# Merge with spatial data
oso_hist_geom_full = obesity_data_sf_2023_OSO %>%
  inner_join(z_scores_change, by = "SCHOOL")

tmap_mode("view")

oso_hist_geom = oso_hist_geom_full %>%
  dplyr::select(c("PT_ID", "SCHOOL", "geometry", "z_change"))


# School obesity map plot (z-score change)
ura_regions_map +
  tm_shape(oso_hist_geom) +
  tm_symbols(size = 0.5, fill = "z_change", fill.scale = tm_scale(values = "brewer.yl_or_rd")) +
  tm_title("Graph of Z-score Changes in Obesity Prevalence for Primary Schools")


```
The plot contains the Z-score changes for each Primary School, with darker red colours representing worsening obesity levels and lighter colours representing improving obesity levels.


```{r}
# by Primary schools
# obesity_pri_sch_jitter <- st_jitter(obesity_pri_sch) 
del_nb_pri_z <- tri2nb(st_coordinates(oso_hist_geom), 
                     row.names = oso_hist_geom$PT_ID) 
pri_map <- tm_shape(nb2lines(del_nb_pri_z, coords = st_geometry(obesity_pri_sch))) +
  tm_lines(lwd = 2) + pri_sch_map

# by Primary schools
if (require(dbscan, quietly=TRUE)) {
  soi_nb_pri_z <- graph2nb(soi.graph(del_nb_pri_z, st_geometry(oso_hist_geom)))
} else {
  soi_nb = NULL
}
pri_map_z <- tm_shape(nb2lines(soi_nb_pri_z, coords = st_geometry(oso_hist_geom))) +
  tm_lines(lwd = 2) + pri_sch_map


# by Primary schools
(soi_lw_pri_z <- nb2listw(soi_nb_pri_z, style = "W"))
soi_lw_B_pri_z <- nb2listw(soi_nb_pri_z, style = "B")

# Setting an overweight cutoff point
Z_CHANGE_CUTOFF_INCREASE <- 1 #increase in obesity levels before and after 2019
Z_CHANGE_CUTOFF_DECREASE <- -1 #decrease in obesity levels before and after 2019

# by Primary school - with increased obesity levels
oso_hist_geom1 = oso_hist_geom %>%
  filter(z_change > 0)
oso_hist_geom1$z_change_high_increase <- 
  as.factor(oso_hist_geom1$z_change > Z_CHANGE_CUTOFF_INCREASE)
pri_map_z_increase <- ura_regions_map + oso_hist_geom1 %>% 
  tm_shape(name = "Overweight prevalence") + 
  tm_symbols(
    fill = "z_change_high_increase", 
    size = "z_change", size.scale = tm_scale_continuous(values.scale = 0.8),
    size.legend = tm_legend_hide()) +
  tm_title("Primary Schools with Worsening Obesity Levels")

# by Primary school - Decrease in Obesity Levels
oso_hist_geom3 = oso_hist_geom %>%
  filter(z_change < 0) %>%
  mutate(z_change = abs(z_change))

oso_hist_geom3$z_change_high_decrease <- 
  as.factor(oso_hist_geom3$z_change > Z_CHANGE_CUTOFF_DECREASE_1)
pri_map_z_decrease1 <- ura_regions_map + oso_hist_geom3 %>% 
  tm_shape(name = "Overweight prevalence") + 
  tm_symbols(
    fill = "z_change_high_decrease", 
    size = "z_change", size.scale = tm_scale_continuous(values.scale = 0.8),
    size.legend = tm_legend_hide()) +
  tm_title("Primary Schools with Improving Obesity Levels")


#Maps:
pri_map_z_decrease1
pri_map_z_increase
```
