# Data loading, cleaning and transformation

## Loading the data

Change the file paths accordingly

```{r}
# Loading libraries to work with spatial data
library(tidyverse); library(sf); library(tmap); library(aspace)

# Loading Singapore URA subzone boundary data
sg_ura_boundaries <- 
  st_read("MasterPlan2014SubzoneBoundaryWebSHP/MP14_SUBZONE_WEB_PL.shp") %>% 
  st_make_valid()

# Saving CRS provided by SG boundary map
sg_crs <- st_crs(sg_ura_boundaries)

# Loading cleaned obesity data from HPB and giving spatial awareness
obesity_data <- 
  # "#N/A" values converted to "NA" for R to be able to read it
  read.csv("obesity.csv", na.strings = "#N/A") %>% 
  st_as_sf(coords = c("longitude","latitude"), crs = 4326) %>% 
  st_transform(crs = sg_crs) %>% 
  st_make_valid()

# Loading cleaned HMSP data from HPB and giving spatial awareness
hmsp_data_sf <- 
  read.csv("hmsp_tier_pri_sec.csv") %>% 
  st_as_sf(coords = c("longitude","latitude"), crs = 4326) %>% 
  st_transform(crs = sg_crs) %>% 
  st_make_valid()

# Checking that all CRS are matching
isTRUE(all.equal(st_crs(sg_ura_boundaries), st_crs(obesity_data), st_crs(hmsp_data_sf)))
```

## Transforming data to be usable for analysis

```{r}
obesity_data_sf <- obesity_data %>% 
  pivot_longer(
    # pivot_longer to separate obesity data columns into a tidy format
    cols = starts_with("X"),
    names_to = c("YEAR", "CATEGORY"),
    names_prefix = "X",
    names_sep = "_",
    names_transform = list(YEAR = as.integer),
    values_to = "COUNT"
    ) %>% 
  mutate(
    # Transform obesity count and school enrolment into an obesity prevalence figure
    PREVALENCE = COUNT / ENROLMENT
    )
```

# Exploratory data analysis (by Prof)

```{r}
tmap_mode("view")
tm_shape(sg_ura_boundaries) + tm_borders() +
  tm_shape(hmsp_data_sf) +
  tm_symbols(size = 0.3, fill = "TIER", 
             fill.scale = tm_scale(values = "brewer.set1"), 
             fill.legend = tm_legend(title = "HMSP Tiers"))

tm_shape(sg_ura_boundaries) + tm_fill() + tm_borders() +
  tm_shape(hmsp_data_sf) +
  tm_symbols(size = 0.3, fill = "ZONE", 
             fill.scale = tm_scale(values = "brewer.set1"), 
             fill.legend = tm_legend(title = "School zones"))

tm_shape(sg_ura_boundaries) + tm_fill() + tm_borders() +
  tm_shape(hmsp_data_sf) +
  tm_symbols(size = 0.3, fill = "CLUSTER", 
             fill.scale = tm_scale(values = "brewer.set1"), 
             fill.legend = tm_legend(title = "School clusters")) +
  tm_facets_wrap(by = "ZONE")
```

# Obesity profile in Singapore (Colin)

## Singapore maps

```{r}
tmap_mode("view")

# Singapore region map
sg_region_map <- tm_shape(sg_ura_boundaries) + tm_polygons(
  col = "grey", fill = "REGION_N", fill_alpha = 0.25, 
  fill.legend = tm_legend(title = "Region")
    )

# Singapore planning area map
sg_planning_map <- tm_shape(sg_ura_boundaries) + tm_polygons(
  col = "grey", fill = "PLN_AREA_N", fill_alpha = 0.25, 
  fill.legend = tm_legend_hide()
  )

sg_subzone_map <- tm_shape(sg_ura_boundaries) + tm_polygons(
  col = "grey", fill = "SUBZONE_N", fill_alpha = 0.25, 
  fill.legend = tm_legend_hide()
  )
```

## Obesity maps

```{r}
# for now, filter for 2023 data and overweight and severely overweight
obesity_filtered <- obesity_data_sf %>% 
  filter(YEAR == 2023, CATEGORY == "OSO")

# Overview of overweight prevalence levels in schools
sg_region_map +
  tm_shape(obesity_filtered) +
  tm_symbols(
    size = 0.5,
    fill = "PREVALENCE", 
    # a green-red diverging scale to indicate severity of overweight prevalence
    fill.scale = tm_scale_continuous(values = "-brewer.rd_yl_gn"), 
    fill.legend = tm_legend(
      title = "Overweight prevalence by school",
      orientation = "landscape", 
      item.height	= 0.5, item.width = 2.1
      )
    )

# Layer by primary and secondary schools

# Aggregate overweight count by 1. URA subzone, 2. URA planning area, 3. URA region, 4. MOE school zone, 5. MOE school cluster. Display the overweight prevalence level

# Try visualising obesity data in a chloropleth map
```

# Income distribution (Lucas)

```{r}

```

# Food and Nutrition (Nina)

```{r}

```

# Physical activity (Qasim)

```{r}
# Loading school co-curricular activities data
school_ccas <- 
  read.csv("CocurricularactivitiesCCAs.csv") %>% 
  group_by(school_name) %>% 
  summarise(
    total = n(),
    physical_sports_count = sum(cca_grouping_desc == "PHYSICAL SPORTS"),
    percentage_physical_sports = (physical_sports_count / total)
  ) %>% 
  select(school_name, percentage_physical_sports)

obesity_joined_sports_data <- 
  obesity_data_sf %>% left_join(school_ccas, by = join_by(SCHOOL == school_name))
```

# Other Useful stuff

```{r}
tmap_mode("view")
tmap_mode("plot")
# tmap_save(tmap_object, 'xx.jpg') # for saving maps as images
cols4all::c4a_gui() # colour scales
RColorBrewer::display.brewer.all()
```
